### ISSUE TITLE
Redundant final case object for Ratings

### ISSUE THREAD

**Issue by spockz** [underscoreio/scalax15-slick#2]
The `final` keyword in the rating objects definitions are redundant:

``` scala
final case object Awesome extends Rating(5)
final case object Good    extends Rating(4)
final case object NotBad  extends Rating(3)
final case object Meh     extends Rating(2)
final case object Aaargh  extends Rating(1)
```

**Comment by d6y** [comment]
Thank you: we add final to be clear we don't expect subclasses. There's a note here about it: https://underscore.io/blog/posts/2015/06/04/more-on-sealed.html#why-you-want-to-use-final

Unless this is causing a problem, I suggest we leave the code as is. Please feel free to re-open if I've missed the point here!
